/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0-alpha1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Camunda.Http.Api.Client;
using Camunda.Http.Api.Model;

namespace Camunda.Http.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHistoricDecisionDefinitionApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Cleanable Decision Instance Report
        /// </summary>
        /// <remarks>
        /// Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;</returns>
        List<CleanableHistoricDecisionInstanceReportResultDto> GetCleanableHistoricDecisionInstanceReport(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?));

        /// <summary>
        /// Get Cleanable Decision Instance Report
        /// </summary>
        /// <remarks>
        /// Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>ApiResponse of List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;</returns>
        ApiResponse<List<CleanableHistoricDecisionInstanceReportResultDto>> GetCleanableHistoricDecisionInstanceReportWithHttpInfo(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?));
        /// <summary>
        /// Get Cleanable Decision Instance Report Count
        /// </summary>
        /// <remarks>
        /// Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <returns>CountResultDto</returns>
        CountResultDto GetCleanableHistoricDecisionInstanceReportCount(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?));

        /// <summary>
        /// Get Cleanable Decision Instance Report Count
        /// </summary>
        /// <remarks>
        /// Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <returns>ApiResponse of CountResultDto</returns>
        ApiResponse<CountResultDto> GetCleanableHistoricDecisionInstanceReportCountWithHttpInfo(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHistoricDecisionDefinitionApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Cleanable Decision Instance Report
        /// </summary>
        /// <remarks>
        /// Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;</returns>
        System.Threading.Tasks.Task<List<CleanableHistoricDecisionInstanceReportResultDto>> GetCleanableHistoricDecisionInstanceReportAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Cleanable Decision Instance Report
        /// </summary>
        /// <remarks>
        /// Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CleanableHistoricDecisionInstanceReportResultDto>>> GetCleanableHistoricDecisionInstanceReportWithHttpInfoAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Cleanable Decision Instance Report Count
        /// </summary>
        /// <remarks>
        /// Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CountResultDto</returns>
        System.Threading.Tasks.Task<CountResultDto> GetCleanableHistoricDecisionInstanceReportCountAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Cleanable Decision Instance Report Count
        /// </summary>
        /// <remarks>
        /// Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CountResultDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CountResultDto>> GetCleanableHistoricDecisionInstanceReportCountWithHttpInfoAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHistoricDecisionDefinitionApi : IHistoricDecisionDefinitionApiSync, IHistoricDecisionDefinitionApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class HistoricDecisionDefinitionApi : IDisposable, IHistoricDecisionDefinitionApi
    {
        private Camunda.Http.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricDecisionDefinitionApi"/> class.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <returns></returns>
        public HistoricDecisionDefinitionApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricDecisionDefinitionApi"/> class.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public HistoricDecisionDefinitionApi(String basePath)
        {
            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                new Camunda.Http.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricDecisionDefinitionApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public HistoricDecisionDefinitionApi(Camunda.Http.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricDecisionDefinitionApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HistoricDecisionDefinitionApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricDecisionDefinitionApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HistoricDecisionDefinitionApi(HttpClient client, String basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                new Camunda.Http.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricDecisionDefinitionApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HistoricDecisionDefinitionApi(HttpClient client, Camunda.Http.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricDecisionDefinitionApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public HistoricDecisionDefinitionApi(Camunda.Http.Api.Client.ISynchronousClient client, Camunda.Http.Api.Client.IAsynchronousClient asyncClient, Camunda.Http.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Camunda.Http.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Camunda.Http.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Camunda.Http.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Camunda.Http.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Camunda.Http.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;</returns>
        public List<CleanableHistoricDecisionInstanceReportResultDto> GetCleanableHistoricDecisionInstanceReport(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?))
        {
            Camunda.Http.Api.Client.ApiResponse<List<CleanableHistoricDecisionInstanceReportResultDto>> localVarResponse = GetCleanableHistoricDecisionInstanceReportWithHttpInfo(decisionDefinitionIdIn, decisionDefinitionKeyIn, tenantIdIn, withoutTenantId, compact, sortBy, sortOrder, firstResult, maxResults);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>ApiResponse of List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;</returns>
        public Camunda.Http.Api.Client.ApiResponse<List<CleanableHistoricDecisionInstanceReportResultDto>> GetCleanableHistoricDecisionInstanceReportWithHttpInfo(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?))
        {
            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (decisionDefinitionIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionIdIn", decisionDefinitionIdIn));
            }
            if (decisionDefinitionKeyIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionKeyIn", decisionDefinitionKeyIn));
            }
            if (tenantIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "tenantIdIn", tenantIdIn));
            }
            if (withoutTenantId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "withoutTenantId", withoutTenantId));
            }
            if (compact != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "compact", compact));
            }
            if (sortBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "sortBy", sortBy));
            }
            if (sortOrder != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "sortOrder", sortOrder));
            }
            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CleanableHistoricDecisionInstanceReportResultDto>>("/history/decision-definition/cleanable-decision-instance-report", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCleanableHistoricDecisionInstanceReport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<CleanableHistoricDecisionInstanceReportResultDto>> GetCleanableHistoricDecisionInstanceReportAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Camunda.Http.Api.Client.ApiResponse<List<CleanableHistoricDecisionInstanceReportResultDto>> localVarResponse = await GetCleanableHistoricDecisionInstanceReportWithHttpInfoAsync(decisionDefinitionIdIn, decisionDefinitionKeyIn, tenantIdIn, withoutTenantId, compact, sortBy, sortOrder, firstResult, maxResults, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Retrieves a report about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)),  so that you can tune the history time to live. These reports include the count of the finished historic decision instances, cleanable decision instances and basic decision definition data - id, key, name and version. The size of the result set can be retrieved by using the  [Get Cleanable Decision Instance Report Count](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report-count/) method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="sortBy">Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)</param>
        /// <param name="sortOrder">Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CleanableHistoricDecisionInstanceReportResultDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Camunda.Http.Api.Client.ApiResponse<List<CleanableHistoricDecisionInstanceReportResultDto>>> GetCleanableHistoricDecisionInstanceReportWithHttpInfoAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), string sortBy = default(string), string sortOrder = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (decisionDefinitionIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionIdIn", decisionDefinitionIdIn));
            }
            if (decisionDefinitionKeyIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionKeyIn", decisionDefinitionKeyIn));
            }
            if (tenantIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "tenantIdIn", tenantIdIn));
            }
            if (withoutTenantId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "withoutTenantId", withoutTenantId));
            }
            if (compact != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "compact", compact));
            }
            if (sortBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "sortBy", sortBy));
            }
            if (sortOrder != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "sortOrder", sortOrder));
            }
            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<CleanableHistoricDecisionInstanceReportResultDto>>("/history/decision-definition/cleanable-decision-instance-report", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCleanableHistoricDecisionInstanceReport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Count Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <returns>CountResultDto</returns>
        public CountResultDto GetCleanableHistoricDecisionInstanceReportCount(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?))
        {
            Camunda.Http.Api.Client.ApiResponse<CountResultDto> localVarResponse = GetCleanableHistoricDecisionInstanceReportCountWithHttpInfo(decisionDefinitionIdIn, decisionDefinitionKeyIn, tenantIdIn, withoutTenantId, compact);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Count Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <returns>ApiResponse of CountResultDto</returns>
        public Camunda.Http.Api.Client.ApiResponse<CountResultDto> GetCleanableHistoricDecisionInstanceReportCountWithHttpInfo(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?))
        {
            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (decisionDefinitionIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionIdIn", decisionDefinitionIdIn));
            }
            if (decisionDefinitionKeyIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionKeyIn", decisionDefinitionKeyIn));
            }
            if (tenantIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "tenantIdIn", tenantIdIn));
            }
            if (withoutTenantId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "withoutTenantId", withoutTenantId));
            }
            if (compact != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "compact", compact));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<CountResultDto>("/history/decision-definition/cleanable-decision-instance-report/count", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCleanableHistoricDecisionInstanceReportCount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Count Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CountResultDto</returns>
        public async System.Threading.Tasks.Task<CountResultDto> GetCleanableHistoricDecisionInstanceReportCountAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Camunda.Http.Api.Client.ApiResponse<CountResultDto> localVarResponse = await GetCleanableHistoricDecisionInstanceReportCountWithHttpInfoAsync(decisionDefinitionIdIn, decisionDefinitionKeyIn, tenantIdIn, withoutTenantId, compact, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Cleanable Decision Instance Report Count Queries for the number of report results about a decision definition and finished decision instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/latest/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Decision Instance Report](https://docs.camunda.org/manual/latest/reference/rest/history/decision-definition/get-cleanable-decision-instance-report/)  method.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="decisionDefinitionIdIn">Filter by decision definition ids. Must be a comma-separated list of decision definition ids. (optional)</param>
        /// <param name="decisionDefinitionKeyIn">Filter by decision definition keys. Must be a comma-separated list of decision definition keys. (optional)</param>
        /// <param name="tenantIdIn">Filter by a comma-separated list of tenant ids. A decision definition must have one of the given tenant  ids. (optional)</param>
        /// <param name="withoutTenantId">Only include decision definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60;  is the default behavior. (optional)</param>
        /// <param name="compact">Only include decision instances which have more than zero finished instances. Value may only be &#x60;true&#x60;,  as &#x60;false&#x60; is the default behavior. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CountResultDto)</returns>
        public async System.Threading.Tasks.Task<Camunda.Http.Api.Client.ApiResponse<CountResultDto>> GetCleanableHistoricDecisionInstanceReportCountWithHttpInfoAsync(string decisionDefinitionIdIn = default(string), string decisionDefinitionKeyIn = default(string), string tenantIdIn = default(string), bool? withoutTenantId = default(bool?), bool? compact = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (decisionDefinitionIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionIdIn", decisionDefinitionIdIn));
            }
            if (decisionDefinitionKeyIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "decisionDefinitionKeyIn", decisionDefinitionKeyIn));
            }
            if (tenantIdIn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "tenantIdIn", tenantIdIn));
            }
            if (withoutTenantId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "withoutTenantId", withoutTenantId));
            }
            if (compact != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "compact", compact));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CountResultDto>("/history/decision-definition/cleanable-decision-instance-report/count", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCleanableHistoricDecisionInstanceReportCount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
