/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0-alpha1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Camunda.Http.Api.Client;
using Camunda.Http.Api.Model;

namespace Camunda.Http.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISchemaLogApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        List<SchemaLogEntryDto> GetSchemaLog(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?));

        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        ApiResponse<List<SchemaLogEntryDto>> GetSchemaLogWithHttpInfo(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?));
        /// <summary>
        /// Get List (POST)
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        List<SchemaLogEntryDto> QuerySchemaLog(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto));

        /// <summary>
        /// Get List (POST)
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        ApiResponse<List<SchemaLogEntryDto>> QuerySchemaLogWithHttpInfo(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISchemaLogApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        System.Threading.Tasks.Task<List<SchemaLogEntryDto>> GetSchemaLogAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SchemaLogEntryDto>>> GetSchemaLogWithHttpInfoAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get List (POST)
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        System.Threading.Tasks.Task<List<SchemaLogEntryDto>> QuerySchemaLogAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get List (POST)
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SchemaLogEntryDto>>> QuerySchemaLogWithHttpInfoAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISchemaLogApi : ISchemaLogApiSync, ISchemaLogApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SchemaLogApi : IDisposable, ISchemaLogApi
    {
        private Camunda.Http.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <returns></returns>
        public SchemaLogApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SchemaLogApi(String basePath)
        {
            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                new Camunda.Http.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SchemaLogApi(Camunda.Http.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SchemaLogApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SchemaLogApi(HttpClient client, String basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                new Camunda.Http.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SchemaLogApi(HttpClient client, Camunda.Http.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SchemaLogApi(Camunda.Http.Api.Client.ISynchronousClient client, Camunda.Http.Api.Client.IAsynchronousClient asyncClient, Camunda.Http.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Camunda.Http.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Camunda.Http.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Camunda.Http.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Camunda.Http.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Camunda.Http.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get List Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        public List<SchemaLogEntryDto> GetSchemaLog(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?))
        {
            Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = GetSchemaLogWithHttpInfo(version, firstResult, maxResults);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get List Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        public Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>> GetSchemaLogWithHttpInfo(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?))
        {
            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (version != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "version", version));
            }
            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get List Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<SchemaLogEntryDto>> GetSchemaLogAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = await GetSchemaLogWithHttpInfoAsync(version, firstResult, maxResults, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get List Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>>> GetSchemaLogWithHttpInfoAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (version != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "version", version));
            }
            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get List (POST) Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        public List<SchemaLogEntryDto> QuerySchemaLog(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto))
        {
            Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = QuerySchemaLogWithHttpInfo(firstResult, maxResults, schemaLogQueryDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get List (POST) Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        public Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>> QuerySchemaLogWithHttpInfo(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto))
        {
            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }
            localVarRequestOptions.Data = schemaLogQueryDto;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("QuerySchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get List (POST) Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<SchemaLogEntryDto>> QuerySchemaLogAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = await QuerySchemaLogWithHttpInfoAsync(firstResult, maxResults, schemaLogQueryDto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get List (POST) Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Camunda.Http.Api.Client.ApiResponse<List<SchemaLogEntryDto>>> QuerySchemaLogWithHttpInfoAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }
            localVarRequestOptions.Data = schemaLogQueryDto;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("QuerySchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
