/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0-alpha1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Camunda.Http.Api.Client;
using Camunda.Http.Api.Model;

namespace Camunda.Http.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaskIdentityLinkApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add
        /// </summary>
        /// <remarks>
        /// Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns></returns>
        void AddIdentityLink(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto));

        /// <summary>
        /// Add
        /// </summary>
        /// <remarks>
        /// Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddIdentityLinkWithHttpInfo(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto));
        /// <summary>
        /// Delete
        /// </summary>
        /// <remarks>
        /// Removes an identity link from a task by id
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns></returns>
        void DeleteIdentityLink(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto));

        /// <summary>
        /// Delete
        /// </summary>
        /// <remarks>
        /// Removes an identity link from a task by id
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteIdentityLinkWithHttpInfo(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto));
        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <returns>List&lt;IdentityLinkDto&gt;</returns>
        List<IdentityLinkDto> GetIdentityLinks(string id, string type = default(string));

        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <returns>ApiResponse of List&lt;IdentityLinkDto&gt;</returns>
        ApiResponse<List<IdentityLinkDto>> GetIdentityLinksWithHttpInfo(string id, string type = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaskIdentityLinkApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Add
        /// </summary>
        /// <remarks>
        /// Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddIdentityLinkAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add
        /// </summary>
        /// <remarks>
        /// Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddIdentityLinkWithHttpInfoAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete
        /// </summary>
        /// <remarks>
        /// Removes an identity link from a task by id
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteIdentityLinkAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete
        /// </summary>
        /// <remarks>
        /// Removes an identity link from a task by id
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteIdentityLinkWithHttpInfoAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;IdentityLinkDto&gt;</returns>
        System.Threading.Tasks.Task<List<IdentityLinkDto>> GetIdentityLinksAsync(string id, string type = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get List
        /// </summary>
        /// <remarks>
        /// Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </remarks>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;IdentityLinkDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<IdentityLinkDto>>> GetIdentityLinksWithHttpInfoAsync(string id, string type = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaskIdentityLinkApi : ITaskIdentityLinkApiSync, ITaskIdentityLinkApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TaskIdentityLinkApi : IDisposable, ITaskIdentityLinkApi
    {
        private Camunda.Http.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskIdentityLinkApi"/> class.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <returns></returns>
        public TaskIdentityLinkApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskIdentityLinkApi"/> class.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public TaskIdentityLinkApi(String basePath)
        {
            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                new Camunda.Http.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskIdentityLinkApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an istance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHander</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public TaskIdentityLinkApi(Camunda.Http.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskIdentityLinkApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TaskIdentityLinkApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskIdentityLinkApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TaskIdentityLinkApi(HttpClient client, String basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                new Camunda.Http.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskIdentityLinkApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TaskIdentityLinkApi(HttpClient client, Camunda.Http.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Camunda.Http.Api.Client.Configuration.MergeConfigurations(
                Camunda.Http.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Camunda.Http.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskIdentityLinkApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public TaskIdentityLinkApi(Camunda.Http.Api.Client.ISynchronousClient client, Camunda.Http.Api.Client.IAsynchronousClient asyncClient, Camunda.Http.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Camunda.Http.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Camunda.Http.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Camunda.Http.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Camunda.Http.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Camunda.Http.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Camunda.Http.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Add Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns></returns>
        public void AddIdentityLink(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto))
        {
            AddIdentityLinkWithHttpInfo(id, identityLinkDto);
        }

        /// <summary>
        /// Add Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Camunda.Http.Api.Client.ApiResponse<Object> AddIdentityLinkWithHttpInfo(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Camunda.Http.Api.Client.ApiException(400, "Missing required parameter 'id' when calling TaskIdentityLinkApi->AddIdentityLink");

            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Camunda.Http.Api.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = identityLinkDto;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/task/{id}/identity-links", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddIdentityLink", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddIdentityLinkAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await AddIdentityLinkWithHttpInfoAsync(id, identityLinkDto, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Add Adds an identity link to a task by id. Can be used to link any user or group to a task and specify a relation.
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add a link to.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Camunda.Http.Api.Client.ApiResponse<Object>> AddIdentityLinkWithHttpInfoAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Camunda.Http.Api.Client.ApiException(400, "Missing required parameter 'id' when calling TaskIdentityLinkApi->AddIdentityLink");


            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Camunda.Http.Api.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = identityLinkDto;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/task/{id}/identity-links", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddIdentityLink", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Removes an identity link from a task by id
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns></returns>
        public void DeleteIdentityLink(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto))
        {
            DeleteIdentityLinkWithHttpInfo(id, identityLinkDto);
        }

        /// <summary>
        /// Delete Removes an identity link from a task by id
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Camunda.Http.Api.Client.ApiResponse<Object> DeleteIdentityLinkWithHttpInfo(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Camunda.Http.Api.Client.ApiException(400, "Missing required parameter 'id' when calling TaskIdentityLinkApi->DeleteIdentityLink");

            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Camunda.Http.Api.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = identityLinkDto;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/task/{id}/identity-links/delete", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteIdentityLink", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Removes an identity link from a task by id
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteIdentityLinkAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteIdentityLinkWithHttpInfoAsync(id, identityLinkDto, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete Removes an identity link from a task by id
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to remove a link from.</param>
        /// <param name="identityLinkDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Camunda.Http.Api.Client.ApiResponse<Object>> DeleteIdentityLinkWithHttpInfoAsync(string id, IdentityLinkDto identityLinkDto = default(IdentityLinkDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Camunda.Http.Api.Client.ApiException(400, "Missing required parameter 'id' when calling TaskIdentityLinkApi->DeleteIdentityLink");


            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Camunda.Http.Api.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = identityLinkDto;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/task/{id}/identity-links/delete", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteIdentityLink", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get List Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <returns>List&lt;IdentityLinkDto&gt;</returns>
        public List<IdentityLinkDto> GetIdentityLinks(string id, string type = default(string))
        {
            Camunda.Http.Api.Client.ApiResponse<List<IdentityLinkDto>> localVarResponse = GetIdentityLinksWithHttpInfo(id, type);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get List Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <returns>ApiResponse of List&lt;IdentityLinkDto&gt;</returns>
        public Camunda.Http.Api.Client.ApiResponse<List<IdentityLinkDto>> GetIdentityLinksWithHttpInfo(string id, string type = default(string))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Camunda.Http.Api.Client.ApiException(400, "Missing required parameter 'id' when calling TaskIdentityLinkApi->GetIdentityLinks");

            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Camunda.Http.Api.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<IdentityLinkDto>>("/task/{id}/identity-links", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetIdentityLinks", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get List Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;IdentityLinkDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<IdentityLinkDto>> GetIdentityLinksAsync(string id, string type = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Camunda.Http.Api.Client.ApiResponse<List<IdentityLinkDto>> localVarResponse = await GetIdentityLinksWithHttpInfoAsync(id, type, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get List Gets the identity links for a task by id, which are the users and groups that are in *some* relation to it (including assignee and owner).
        /// </summary>
        /// <exception cref="Camunda.Http.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the identity links for.</param>
        /// <param name="type">Filter by the type of links to include. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;IdentityLinkDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Camunda.Http.Api.Client.ApiResponse<List<IdentityLinkDto>>> GetIdentityLinksWithHttpInfoAsync(string id, string type = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Camunda.Http.Api.Client.ApiException(400, "Missing required parameter 'id' when calling TaskIdentityLinkApi->GetIdentityLinks");


            Camunda.Http.Api.Client.RequestOptions localVarRequestOptions = new Camunda.Http.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Camunda.Http.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Camunda.Http.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Camunda.Http.Api.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Camunda.Http.Api.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<IdentityLinkDto>>("/task/{id}/identity-links", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetIdentityLinks", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
