/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0-alpha1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Camunda.Http.Api.Client.OpenAPIDateConverter;

namespace Camunda.Http.Api.Model
{
    /// <summary>
    /// AuthorizationCheckResultDto
    /// </summary>
    [DataContract(Name = "AuthorizationCheckResultDto")]
    public partial class AuthorizationCheckResultDto : IEquatable<AuthorizationCheckResultDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationCheckResultDto" /> class.
        /// </summary>
        /// <param name="permissionName">Name of the permission which was checked..</param>
        /// <param name="resourceName">The name of the resource for which the permission check was performed..</param>
        /// <param name="resourceId">The id of the resource for which the permission check was performed..</param>
        /// <param name="isAuthorized">True / false for isAuthorized..</param>
        public AuthorizationCheckResultDto(string permissionName = default(string), string resourceName = default(string), string resourceId = default(string), bool? isAuthorized = default(bool?))
        {
            this.PermissionName = permissionName;
            this.ResourceName = resourceName;
            this.ResourceId = resourceId;
            this.IsAuthorized = isAuthorized;
        }

        /// <summary>
        /// Name of the permission which was checked.
        /// </summary>
        /// <value>Name of the permission which was checked.</value>
        [DataMember(Name = "permissionName", EmitDefaultValue = true)]
        public string PermissionName { get; set; }

        /// <summary>
        /// The name of the resource for which the permission check was performed.
        /// </summary>
        /// <value>The name of the resource for which the permission check was performed.</value>
        [DataMember(Name = "resourceName", EmitDefaultValue = true)]
        public string ResourceName { get; set; }

        /// <summary>
        /// The id of the resource for which the permission check was performed.
        /// </summary>
        /// <value>The id of the resource for which the permission check was performed.</value>
        [DataMember(Name = "resourceId", EmitDefaultValue = true)]
        public string ResourceId { get; set; }

        /// <summary>
        /// True / false for isAuthorized.
        /// </summary>
        /// <value>True / false for isAuthorized.</value>
        [DataMember(Name = "isAuthorized", EmitDefaultValue = true)]
        public bool? IsAuthorized { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuthorizationCheckResultDto {\n");
            sb.Append("  PermissionName: ").Append(PermissionName).Append("\n");
            sb.Append("  ResourceName: ").Append(ResourceName).Append("\n");
            sb.Append("  ResourceId: ").Append(ResourceId).Append("\n");
            sb.Append("  IsAuthorized: ").Append(IsAuthorized).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthorizationCheckResultDto);
        }

        /// <summary>
        /// Returns true if AuthorizationCheckResultDto instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthorizationCheckResultDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthorizationCheckResultDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PermissionName == input.PermissionName ||
                    (this.PermissionName != null &&
                    this.PermissionName.Equals(input.PermissionName))
                ) && 
                (
                    this.ResourceName == input.ResourceName ||
                    (this.ResourceName != null &&
                    this.ResourceName.Equals(input.ResourceName))
                ) && 
                (
                    this.ResourceId == input.ResourceId ||
                    (this.ResourceId != null &&
                    this.ResourceId.Equals(input.ResourceId))
                ) && 
                (
                    this.IsAuthorized == input.IsAuthorized ||
                    (this.IsAuthorized != null &&
                    this.IsAuthorized.Equals(input.IsAuthorized))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PermissionName != null)
                    hashCode = hashCode * 59 + this.PermissionName.GetHashCode();
                if (this.ResourceName != null)
                    hashCode = hashCode * 59 + this.ResourceName.GetHashCode();
                if (this.ResourceId != null)
                    hashCode = hashCode * 59 + this.ResourceId.GetHashCode();
                if (this.IsAuthorized != null)
                    hashCode = hashCode * 59 + this.IsAuthorized.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
