/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0-alpha1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Camunda.Http.Api.Client.OpenAPIDateConverter;

namespace Camunda.Http.Api.Model
{
    /// <summary>
    /// ConditionQueryParameterDto
    /// </summary>
    [DataContract(Name = "ConditionQueryParameterDto")]
    public partial class ConditionQueryParameterDto : IEquatable<ConditionQueryParameterDto>, IValidatableObject
    {
        /// <summary>
        /// Comparison operator to be used
        /// </summary>
        /// <value>Comparison operator to be used</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OperatorEnum
        {
            /// <summary>
            /// Enum Eq for value: eq
            /// </summary>
            [EnumMember(Value = "eq")]
            Eq = 1,

            /// <summary>
            /// Enum Neq for value: neq
            /// </summary>
            [EnumMember(Value = "neq")]
            Neq = 2,

            /// <summary>
            /// Enum Gt for value: gt
            /// </summary>
            [EnumMember(Value = "gt")]
            Gt = 3,

            /// <summary>
            /// Enum Gteq for value: gteq
            /// </summary>
            [EnumMember(Value = "gteq")]
            Gteq = 4,

            /// <summary>
            /// Enum Lt for value: lt
            /// </summary>
            [EnumMember(Value = "lt")]
            Lt = 5,

            /// <summary>
            /// Enum Lteq for value: lteq
            /// </summary>
            [EnumMember(Value = "lteq")]
            Lteq = 6,

            /// <summary>
            /// Enum Like for value: like
            /// </summary>
            [EnumMember(Value = "like")]
            Like = 7

        }


        /// <summary>
        /// Comparison operator to be used
        /// </summary>
        /// <value>Comparison operator to be used</value>
        [DataMember(Name = "operator", EmitDefaultValue = true)]
        public OperatorEnum? Operator { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConditionQueryParameterDto" /> class.
        /// </summary>
        /// <param name="_operator">Comparison operator to be used.</param>
        /// <param name="value">The variable value, could be of type boolean, string or number.</param>
        public ConditionQueryParameterDto(OperatorEnum? _operator = default(OperatorEnum?), Object value = default(Object))
        {
            this.Operator = _operator;
            this.Value = value;
        }

        /// <summary>
        /// The variable value, could be of type boolean, string or number
        /// </summary>
        /// <value>The variable value, could be of type boolean, string or number</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConditionQueryParameterDto {\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConditionQueryParameterDto);
        }

        /// <summary>
        /// Returns true if ConditionQueryParameterDto instances are equal
        /// </summary>
        /// <param name="input">Instance of ConditionQueryParameterDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConditionQueryParameterDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Operator == input.Operator ||
                    this.Operator.Equals(input.Operator)
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Operator.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
