/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0-alpha1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Camunda.Http.Api.Client.OpenAPIDateConverter;

namespace Camunda.Http.Api.Model
{
    /// <summary>
    /// MigrationInstructionDto
    /// </summary>
    [DataContract(Name = "MigrationInstructionDto")]
    public partial class MigrationInstructionDto : IEquatable<MigrationInstructionDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MigrationInstructionDto" /> class.
        /// </summary>
        /// <param name="sourceActivityIds">The activity ids from the source process definition being mapped..</param>
        /// <param name="targetActivityIds">The activity ids from the target process definition being mapped..</param>
        /// <param name="updateEventTrigger">Configuration flag whether event triggers defined are going to be updated during migration..</param>
        public MigrationInstructionDto(List<string> sourceActivityIds = default(List<string>), List<string> targetActivityIds = default(List<string>), bool? updateEventTrigger = default(bool?))
        {
            this.SourceActivityIds = sourceActivityIds;
            this.TargetActivityIds = targetActivityIds;
            this.UpdateEventTrigger = updateEventTrigger;
        }

        /// <summary>
        /// The activity ids from the source process definition being mapped.
        /// </summary>
        /// <value>The activity ids from the source process definition being mapped.</value>
        [DataMember(Name = "sourceActivityIds", EmitDefaultValue = true)]
        public List<string> SourceActivityIds { get; set; }

        /// <summary>
        /// The activity ids from the target process definition being mapped.
        /// </summary>
        /// <value>The activity ids from the target process definition being mapped.</value>
        [DataMember(Name = "targetActivityIds", EmitDefaultValue = true)]
        public List<string> TargetActivityIds { get; set; }

        /// <summary>
        /// Configuration flag whether event triggers defined are going to be updated during migration.
        /// </summary>
        /// <value>Configuration flag whether event triggers defined are going to be updated during migration.</value>
        [DataMember(Name = "updateEventTrigger", EmitDefaultValue = true)]
        public bool? UpdateEventTrigger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MigrationInstructionDto {\n");
            sb.Append("  SourceActivityIds: ").Append(SourceActivityIds).Append("\n");
            sb.Append("  TargetActivityIds: ").Append(TargetActivityIds).Append("\n");
            sb.Append("  UpdateEventTrigger: ").Append(UpdateEventTrigger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MigrationInstructionDto);
        }

        /// <summary>
        /// Returns true if MigrationInstructionDto instances are equal
        /// </summary>
        /// <param name="input">Instance of MigrationInstructionDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MigrationInstructionDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SourceActivityIds == input.SourceActivityIds ||
                    this.SourceActivityIds != null &&
                    input.SourceActivityIds != null &&
                    this.SourceActivityIds.SequenceEqual(input.SourceActivityIds)
                ) && 
                (
                    this.TargetActivityIds == input.TargetActivityIds ||
                    this.TargetActivityIds != null &&
                    input.TargetActivityIds != null &&
                    this.TargetActivityIds.SequenceEqual(input.TargetActivityIds)
                ) && 
                (
                    this.UpdateEventTrigger == input.UpdateEventTrigger ||
                    (this.UpdateEventTrigger != null &&
                    this.UpdateEventTrigger.Equals(input.UpdateEventTrigger))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SourceActivityIds != null)
                    hashCode = hashCode * 59 + this.SourceActivityIds.GetHashCode();
                if (this.TargetActivityIds != null)
                    hashCode = hashCode * 59 + this.TargetActivityIds.GetHashCode();
                if (this.UpdateEventTrigger != null)
                    hashCode = hashCode * 59 + this.UpdateEventTrigger.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
